#!/bin/sh
#
# supervisor - this script starts and stops the supervisor daemon
#
# chkconfig:   - 85 15
# description:  Nginx is an HTTP(S) server, HTTP(S) reverse \
#               proxy and IMAP/POP3 proxy server
# processname: supervisor
# config:      /etc/supervisor/supervisor.conf
# config:      /etc/sysconfig/supervisor
# pidfile:     /var/run/supervisor.pid

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

supervisor="/usr/local/bin/supervisord"
supervisor_ctrl="/usr/local/bin/supervisord"
prog=$(basename $supervisor)
sysconfig="/etc/sysconfig/$prog"
lockfile="/var/lock/subsys/supervisord.lock"
pidfile="/var/run/${prog}.pid"

SUPERVISOR_CONF_FILE="/data/supervisor.conf"
echo "Using: $supervisor"

[ -f $sysconfig ] && . $sysconfig


start() {
    echo -n $"Starting $prog: "
    [ -x $supervisor ] || exit 5
    [ -f $SUPERVISOR_CONF_FILE ] || exit 6
    daemon --pidfile=$pidfile $supervisor -c $SUPERVISOR_CONF_FILE > /dev/null
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    configtest_q || return 6
    echo -n $"Reloading $prog: with new config"
    $supervisor_ctrl -c $SUPERVISOR_CONF_FILE update
    killproc -p $pidfile $prog -HUP
    echo
}

rh_status() {
    if [ -f "$lockfile" ]; then
        echo -n "$prog is running"; success; echo
        return 0
    else
        echo -n "$prog is NOT running"; failure; echo
        return 1
    fi
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    status|status_q)
        rh_$1
        ;;
    condrestart|try-restart)
        rh_status_q || exit 7
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|reload|status|restart}"
        exit 2
esac
